version: "3.8"

services:
  db:
    image: mysql:8
    container_name: training-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_DATABASE:
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build: .
    container_name: training-backend
    restart: always
    environment:
      DATABASE_URL: "mysql://training:training123@db:3306/trainingdb"
    ports:
      - "3000:3000"
    depends_on:
      - db

  prisma-studio:
    image: node:20
    container_name: prisma-studio
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npx prisma studio"
    ports:
      - "5555:5555"
    depends_on:
      - db
